import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    appName: 'CropCare AI',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    name: 'Full Name',
    emailPhone: 'Phone or Email',
    password: 'Password',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    scan: 'Scan',
    history: 'History',
    home: 'Home',
    uploadTitle: 'Upload Leaf Image',
    uploadDesc: 'Take a photo of the affected plant leaf to detect diseases.',
    analyze: 'Analyze Image',
    analyzing: 'Analyzing...',
    retake: 'Retake',
    results: 'Detection Results',
    healthy: 'Healthy',
    disease: 'Disease Detected',
    warning: 'Warning',
    confidence: 'Confidence',
    weatherAlert: 'Weather Alert',
    advice: 'Treatment Advice',
    fertilizer: 'Fertilizer Recommendation',
    temp: 'Temperature',
    rain: 'Rain Probability',
    smartAlertRain: 'Rain expected: Avoid spraying fertilizer today.',
    smartAlertHeat: 'High heat: Increase irrigation to protect crops.',
    smartAlertClear: 'Weather is clear: Good time for maintenance.',
    voiceOutput: 'Listen to Results',
    placeholderName: 'Enter your name',
    placeholderEmail: 'Enter phone or email',
    placeholderPass: 'Enter password',
    landSize: 'Land Size (Acres)',
    placeholderLand: 'How many acres of land?',
    cropDetails: 'Crop Details',
    cropVariety: 'Crop Variety',
    soilType: 'Soil Type',
    plantingDate: 'Planting Date',
    next: 'Next',
    dosageInfo: 'Fertilizer Dosage',
    totalQuantity: 'Total Quantity Needed',
    buyNow: 'Buy Fertilizer Online',
    profile: 'Farmer Profile',
    knowledgeHub: 'Knowledge Hub',
    perAcre: 'per acre',
    totalFor: 'Total for',
    acres: 'acres',
    welcomeTitle: 'wELCOME',
    welcomeSubtitle: 'Nurturing the future of agriculture, one leaf at a time.',
    welcomeMessage: 'Your AI-powered companion for smarter farming. Detect diseases, get weather alerts, and optimize fertilizer dosage all in one place.',
    getStarted: 'Start Growing',
    joinCommunity: 'Join the Community',
    knowledgeHubTitle: 'CropCare Knowledge Hub',
    organicCorner: 'Organic Corner',
    organicDesc: 'Sustainable farming for a healthier planet and higher value crops.',
    exploreOrganic: 'Explore Organic Methods',
    composting: 'Composting',
    compostingDesc: 'Turn waste into gold for your soil.',
    bioPesticides: 'Bio-Pesticides',
    bioPesticidesDesc: 'Safe control for your crops.',
    cropRotation: 'Crop Rotation',
    cropRotationDesc: 'Natural nutrient management.',
    ecoFertilizers: 'Eco-Fertilizers',
    ecoFertilizersDesc: 'Balanced growth, zero chemicals.',
    watchVideo: 'Watch Video',
    encyclopedia: 'Encyclopedia',
    weatherAdvisory: 'Weather Advisory',
    seasonalGuide: 'Seasonal Guide',
    pestId: 'Pest ID',
    soilHealth: 'Soil Health',
    searchPlaceholder: 'Search diseases or crops...',
    riskLevel: 'Risk',
    viewDetails: 'View Details',
    preventionTreatment: 'Prevention & Treatment',
    recommendedTreatment: 'Recommended Treatment',
    preventiveAction: 'Preventive Action',
    symptoms: 'Symptoms',
    causes: 'Causes',
    marketEdge: 'Market Edge',
    liveMarketPrices: 'Live Market Prices',
    wheat: 'Wheat',
    rice: 'Rice',
    tools: 'Tools',
    earlyDetection: 'Early Detection',
    earlyDetectionDesc: 'Identify diseases before they spread.',
    pestControl: 'Pest Control',
    pestControlDesc: 'Get verified treatment suggestions.',
    welcomeBack: 'Welcome Back',
    cotton: 'Cotton',
    quintal: '/ quintal',
  },
  bn: {
    appName: 'ক্রপকেয়ার AI',
    login: 'লগ-ইন',
    signup: 'নিবন্ধন করুন',
    logout: 'লগ-আউট',
    name: 'পুরো নাম',
    emailPhone: 'ফোন বা ইমেল',
    password: 'পাসওয়ার্ড',
    noAccount: "অ্যাকাউন্ট নেই?",
    hasAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    scan: 'স্ক্যান',
    history: 'ইতিহাস',
    home: 'হোম',
    uploadTitle: 'পাতার ছবি আপলোড করুন',
    uploadDesc: 'রোগ শনাক্ত করতে আক্রান্ত গাছের পাতার ছবি তুলুন।',
    analyze: 'বিশ্লেষণ করুন',
    analyzing: 'বিশ্লেষণ করা হচ্ছে...',
    retake: 'আবার তুলুন',
    results: 'শনাক্তকরণ ফলাফল',
    healthy: 'সুস্থ',
    disease: 'রোগ শনাক্ত হয়েছে',
    warning: 'সতর্কতা',
    confidence: 'নিশ্চয়তা',
    weatherAlert: 'আবহাওয়া সতর্কতা',
    advice: 'চিকিৎসা পরামর্শ',
    fertilizer: 'সার প্রয়োগের পরামর্শ',
    temp: 'তাপমাত্রা',
    rain: 'বৃষ্টির সম্ভাবনা',
    smartAlertRain: 'বৃষ্টির সম্ভাবনা: আজ সার প্রয়োগ এড়িয়ে চলুন।',
    smartAlertHeat: 'প্রচণ্ড তাপ: ফসল রক্ষায় সেচ বাড়ান।',
    smartAlertClear: 'আবহাওয়া পরিষ্কার: রক্ষণাবেক্ষণের জন্য উপযুক্ত সময়।',
    voiceOutput: 'ফলাফল শুনুন',
    placeholderName: 'আপনার নাম লিখুন',
    placeholderEmail: 'ফোন বা ইমেল লিখুন',
    placeholderPass: 'পাসওয়ার্ড লিখুন',
    landSize: 'জমির পরিমাণ (একর)',
    placeholderLand: 'আপনার কত একর জমি আছে?',
    cropDetails: 'ফসলের বিবরণ',
    cropVariety: 'ফসলের ধরন',
    soilType: 'মাটির ধরন',
    plantingDate: 'বপনের তারিখ',
    next: 'পরবর্তী',
    dosageInfo: 'সারের মাত্রা',
    totalQuantity: 'প্রয়োজনীয় মোট পরিমাণ',
    buyNow: 'অনলাইনে সার কিনুন',
    profile: 'কৃষকের প্রোফাইল',
    knowledgeHub: 'তথ্য কেন্দ্র',
    perAcre: 'প্রতি একর',
    totalFor: 'মোট',
    acres: 'একর',
    welcomeTitle: 'স্বাগতম',
    welcomeSubtitle: 'কৃষির ভবিষ্যৎ লালন করছি, প্রতি পাতায়।',
    welcomeMessage: 'স্মার্ট চাষের জন্য আপনার AI-চালিত সঙ্গী। রোগ শনাক্ত করুন, আবহাওয়ার সতর্কতা পান এবং সারের মাত্রা অপ্টিমাইজ করুন সব এক জায়গায়।',
    getStarted: 'চাষ শুরু করুন',
    joinCommunity: 'কমিউনিটিতে যোগ দিন',
    knowledgeHubTitle: 'ক্রপকেয়ার জ্ঞান কেন্দ্র',
    organicCorner: 'জৈব কর্নার',
    organicDesc: 'সুস্থ পৃথিবীর জন্য এবং ফসলের উন্নত মানের জন্য টেকসই চাষাবাদ।',
    exploreOrganic: 'জৈব পদ্ধতিগুলি অন্বেষণ করুন',
    composting: 'কম্পোস্টিং',
    compostingDesc: 'আপনার মাটির জন্য বর্জ্যকে সোনায় পরিণত করুন।',
    bioPesticides: 'জৈব-কীটনাশক',
    bioPesticidesDesc: 'আপনার ফসলের জন্য নিরাপদ নিয়ন্ত্রণ।',
    cropRotation: 'ফসল আবর্তন',
    cropRotationDesc: 'প্রাকৃতিক পুষ্টি ব্যবস্থাপনা।',
    ecoFertilizers: 'পরিবেশ-বান্ধব সার',
    ecoFertilizersDesc: 'ভারসাম্যপূর্ণ বৃদ্ধি, শূন্য রাসায়নিক।',
    watchVideo: 'ভিডিও দেখুন',
    encyclopedia: 'তথ্যকোষ',
    weatherAdvisory: 'আবহাওয়া পরামর্শ',
    seasonalGuide: 'ঋতুভিত্তিক নির্দেশিকা',
    pestId: 'পোকামাকড় শনাক্তকরণ',
    soilHealth: 'মাটির স্বাস্থ্য',
    marketEdge: 'মার্কেট এজ',
    liveMarketPrices: 'লাইভ বাজার মূল্য',
    wheat: 'গম',
    rice: 'ধান',
    tools: 'সরঞ্জাম',
    earlyDetection: 'প্রাথমিক শনাক্তকরণ',
    earlyDetectionDesc: 'ছড়িয়ে পড়ার আগেই রোগ শনাক্ত করুন।',
    pestControl: 'পোকামাকড় নিয়ন্ত্রণ',
    pestControlDesc: 'যাচাইকৃত প্রতিকার পান।',
    welcomeBack: 'আবার স্বাগতম',
    cotton: 'তুলা',
    quintal: '/ কুইন্টাল',
  },
  hi: {
    appName: 'क्रॉपकेयर AI',
    login: 'लॉगिन',
    signup: 'साइन अप करें',
    logout: 'लॉगआउट',
    name: 'पूरा नाम',
    emailPhone: 'फ़ोन या ईमेल',
    password: 'पासवर्ड',
    noAccount: "खाता नहीं है?",
    hasAccount: 'पहले से खाता है?',
    scan: 'स्कैन',
    history: 'इतिहास',
    home: 'होम',
    uploadTitle: 'पत्ती की फोटो अपलोड करें',
    uploadDesc: 'रोगों का पता लगाने के लिए प्रभावित पौधे की पत्ती की फोटो लें।',
    analyze: 'विश्लेषण करें',
    analyzing: 'विश्लेषण हो रहा है...',
    retake: 'फिर से लें',
    results: 'जांच के परिणाम',
    healthy: 'स्वस्थ',
    disease: 'रोग का पता चला',
    warning: 'चेतावनी',
    confidence: 'आत्मविश्वास',
    weatherAlert: 'मौसम की चेतावनी',
    advice: 'उपचार सलाह',
    fertilizer: 'उर्वरक की सलाह',
    temp: 'तापमान',
    rain: 'बारिश की संभावना',
    smartAlertRain: 'बारिश की संभावना: आज उर्वरक छिड़कने से बचें।',
    smartAlertHeat: 'तेज गर्मी: फसलों की रक्षा के लिए सिंचाई बढ़ाएं।',
    smartAlertClear: 'मौसम साफ है: रखरखाव के लिए अच्छा समय है।',
    voiceOutput: 'परिणाम सुनें',
    placeholderName: 'अपना नाम दर्ज करें',
    placeholderEmail: 'फ़ोन या ईमेल दर्ज करें',
    placeholderPass: 'पासवर्ड दर्ज करें',
    landSize: 'भूमि का आकार (एकड़)',
    placeholderLand: 'आपके पास कितनी एकड़ जमीन है?',
    cropDetails: 'फसल का विवरण',
    cropVariety: 'फसल की किस्म',
    soilType: 'मिट्टी का प्रकार',
    plantingDate: 'बुवाई की तारीख',
    next: 'अगला',
    dosageInfo: 'खाद की मात्रा',
    totalQuantity: 'कुल आवश्यक मात्रा',
    buyNow: 'ऑनलाइन खाद खरीदें',
    profile: 'किसान प्रोफाइल',
    knowledgeHub: 'ज्ञान केंद्र',
    perAcre: 'प्रति एकड़',
    totalFor: 'कुल',
    acres: 'एकड़',
    welcomeTitle: 'सुस्वागतम',
    welcomeSubtitle: 'कृषि के भविष्य को संवारना, हर एक पत्ती के साथ।',
    welcomeMessage: 'स्मार्ट खेती के लिए आपका AI-आधारित साथी। रोगों का पता लगाएं, मौसम की चेतावनी पाएं और उर्वरक की मात्रा को अनुकूलित करें - सब एक ही स्थान पर।',
    getStarted: 'खेती शुरू करें',
    joinCommunity: 'समुदाय में शामिल हों',
    knowledgeHubTitle: 'क्रॉपकेयर ज्ञान केंद्र',
    organicCorner: 'जैविक कोना',
    organicDesc: 'स्वस्थ ग्रह और उच्च मूल्य वाली फसलों के लिए टिकाऊ खेती।',
    exploreOrganic: 'जैविक तरीकों का पता लगाएं',
    composting: 'कम्पोस्टिंग',
    compostingDesc: 'अपनी मिट्टी के लिए कचरे को सोने में बदलें।',
    bioPesticides: 'जैव-कीटनाशक',
    bioPesticidesDesc: 'आपकी फसलों के लिए सुरक्षित नियंत्रण।',
    cropRotation: 'फसल चक्र',
    cropRotationDesc: 'प्राकृतिक पोषक तत्व प्रबंधन।',
    ecoFertilizers: 'इको-उर्वरक',
    ecoFertilizersDesc: 'संतुलित विकास, शून्य रसायन।',
    watchVideo: 'वीडियो देखें',
    encyclopedia: 'विश्वकोश',
    weatherAdvisory: 'मौसम सलाह',
    seasonalGuide: 'मौसमी गाइड',
    pestId: 'कीट पहचान',
    soilHealth: 'मिट्टी का स्वास्थ्य',
    marketEdge: 'मार्केट एज',
    liveMarketPrices: 'लाइव बाजार मूल्य',
    wheat: 'गेहूं',
    rice: 'चावल',
    tools: 'उपकरण',
    earlyDetection: 'प्रारंभिक पहचान',
    earlyDetectionDesc: 'बीमारियों को फैलने से पहले पहचानें।',
    pestControl: 'कीट नियंत्रण',
    pestControlDesc: 'सत्यापित उपचार सुझाव प्राप्त करें।',
    welcomeBack: 'फिर से स्वागत है',
    cotton: 'कपास',
    quintal: '/ कुंतल',
  },
  mr: {
    appName: 'क्रॉपकेअर AI',
    login: 'लॉगिन',
    signup: 'नोंदणी करा',
    logout: 'लॉगआउट',
    name: 'पूर्ण नाव',
    emailPhone: 'फोन किंवा ईमेल',
    password: 'पासवर्ड',
    noAccount: "खाते नाही?",
    hasAccount: 'आधीच खाते आहे?',
    scan: 'स्कॅन',
    history: 'इतिहास',
    home: 'होम',
    uploadTitle: 'पानाचे छायाचित्र अपलोड करा',
    uploadDesc: 'रोगांचे निदान करण्यासाठी बाधित रोपाच्या पानाचे छायाचित्र घ्या.',
    analyze: 'विश्लेषण करा',
    analyzing: 'विश्लेषण होत आहे...',
    retake: 'पुन्हा घ्या',
    results: 'तपासणीचे निकाल',
    healthy: 'निरोगी',
    disease: 'रोग आढळला',
    warning: 'इशारा',
    confidence: 'खात्री',
    weatherAlert: 'हवामान इशारा',
    advice: 'उपचार सल्ला',
    fertilizer: 'खताचा सल्ला',
    temp: 'तापमान',
    rain: 'पावसाची शक्यता',
    smartAlertRain: 'पावसाची शक्यता: आज खत फवारणे टाळा.',
    smartAlertHeat: 'प्रचंड उष्णता: पिकांच्या संरक्षणासाठी सिंचन वाढवा.',
    smartAlertClear: 'हवामान स्वच्छ आहे: देखभालीसाठी चांगली वेळ आहे.',
    voiceOutput: 'निकाल ऐका',
    placeholderName: 'तुमचे नाव टाका',
    placeholderEmail: 'फोन किंवा ईमेल टाका',
    placeholderPass: 'पासवर्ड टाका',
    landSize: 'जमिनीचा आकार (एकर)',
    placeholderLand: 'तुमच्याकडे किती एकर जमीन आहे?',
    cropDetails: 'पिकाचा तपशील',
    cropVariety: 'पिकाची जात',
    soilType: 'मातीचा प्रकार',
    plantingDate: 'लागवडीची तारीख',
    next: 'पुढील',
    dosageInfo: 'खताची मात्रा',
    totalQuantity: 'एकूण आवश्यक प्रमाण',
    buyNow: 'ऑनलाइन खत खरेदी करा',
    profile: 'शेतकरी प्रोफाइल',
    knowledgeHub: 'ज्ञान केंद्र',
    perAcre: 'प्रति एकर',
    totalFor: 'एकूण',
    acres: 'एकर',
    welcomeTitle: 'सुस्वागतम',
    welcomeSubtitle: 'शेतीचे भविष्य घडवत आहोत, प्रत्येक पानासोबत।',
    welcomeMessage: 'स्मार्ट शेतीसाठी आपला AI-आधारित सोबती। रोगांचे निदान करा, हवामान इशारे मिळवा आणि खतांचे प्रमाण अचूक करा - सर्व काही एकाच ठिकाणी।',
    getStarted: 'शेती सुरू करा',
    joinCommunity: 'समुदायात सामील व्हा',
    welcomeBack: 'पुन्हा स्वागत आहे',
    cotton: 'कापूस',
    quintal: '/ क्विंटल',
  },
  ta: {
    appName: 'கிராப்கேர் AI',
    login: 'உள்நுழை',
    signup: 'பதிவு செய்',
    logout: 'வெளியேறு',
    name: 'முழு பெயர்',
    emailPhone: 'தொலைபேசி அல்லது மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    noAccount: "கணக்கு இல்லையா?",
    hasAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    scan: 'ஸ்கேன்',
    history: 'வரலாறு',
    home: 'முகப்பு',
    uploadTitle: 'இலை படத்தை பதிவேற்றவும்',
    uploadDesc: 'நோய்களைக் கண்டறிய பாதிக்கப்பட்ட செடியின் இலையை புகைப்படம் எடுக்கவும்.',
    analyze: 'பகுப்பாய்வு செய்',
    analyzing: 'பகுப்பாய்வு செய்கிறது...',
    retake: 'மீண்டும் எடு',
    results: 'கண்டறிதல் முடிவுகள்',
    healthy: 'ஆரோக்கியமானது',
    disease: 'நோய் கண்டறியப்பட்டது',
    warning: 'எச்சரிக்கை',
    confidence: 'நம்பிக்கை',
    weatherAlert: 'வானிலை எச்சரிக்கை',
    advice: 'சிகிச்சை ஆலோசனை',
    fertilizer: 'உர பரிந்துரை',
    temp: 'வெப்பநிலை',
    rain: 'மழை வாய்ப்பு',
    smartAlertRain: 'மழை எதிர்பார்க்கப்படுகிறது: இன்று உரம் தெளிப்பதைத் தவிர்க்கவும்.',
    smartAlertHeat: 'அதிக வெப்பம்: பயிர்களைப் பாதுகாக்க பாசனத்தை அதிகரிக்கவும்.',
    smartAlertClear: 'வானிலை தெளிவாக உள்ளது: பராமரிப்புக்கு நல்ல நேரம்.',
    voiceOutput: 'முடிவுகளைக் கேளுங்கள்',
    placeholderName: 'உங்கள் பெயரை உள்ளிடவும்',
    placeholderEmail: 'தொலைபேசி அல்லது மின்னஞ்சலை உள்ளிடவும்',
    placeholderPass: 'கடவுச்சொல்லை உள்ளிடவும்',
    landSize: 'நில அளவு (ஏக்கர்)',
    placeholderLand: 'உங்களுக்கு எத்தனை ஏக்கர் நிலம் உள்ளது?',
    cropDetails: 'பயிர் விவரங்கள்',
    cropVariety: 'பயிர் வகை',
    soilType: 'மண் வகை',
    plantingDate: 'நடவு தேதி',
    next: 'அடுத்து',
    dosageInfo: 'உர அளவு',
    totalQuantity: 'தேவையான மொத்த அளவு',
    buyNow: 'உரத்தை ஆன்லைனில் வாங்கவும்',
    profile: 'விவசாயி சுயவிவரம்',
    knowledgeHub: 'அறிவு மையம்',
    perAcre: 'ஏக்கருக்கு',
    totalFor: 'மொத்தம்',
    acres: 'ஏக்கர்',
    welcomeTitle: 'வரவேற்கிறோம்',
    welcomeSubtitle: 'விவசாயத்தின் எதிர்காலத்தை வளர்க்கிறோம், ஒவ்வொரு இலையிலும்।',
    welcomeMessage: 'ஸ்மார்ட் விவசாயத்திற்கான உங்கள் AI-இயங்கும் துணை। நோய்களைக் கண்டறியவும், வானிலை எச்சரிக்கைகளைப் பெறவும் மற்றும் உர அளவை மேம்படுத்தவும் - அனைத்தும் ஒரே இடத்தில்।',
    getStarted: 'விவசாயத்தைத் தொடங்குங்கள்',
    joinCommunity: 'சமூகத்தில் இணையுங்கள்',
    welcomeBack: 'மீண்டும் வருக',
    cotton: 'பருத்தி',
    quintal: '/ குவின்டால்',
  },
  te: {
    appName: 'క్రాప్ కేర్ AI',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    logout: 'లాగౌట్',
    name: 'పూర్తి పేరు',
    emailPhone: 'ఫోన్ లేదా ఈమెయిల్',
    password: 'పాస్‌వర్డ్',
    noAccount: "ఖాతా లేదా?",
    hasAccount: 'ముందే ఖాతా ఉందా?',
    scan: 'స్కాన్',
    history: 'చరిత్ర',
    home: 'హోమ్',
    uploadTitle: 'ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి',
    uploadDesc: 'వ్యాధులను గుర్తించడానికి ప్రభావిత మొక్క ఆకును ఫోటో తీయండి.',
    analyze: 'విశ్లేషించండి',
    analyzing: 'విశ్లేషిస్తోంది...',
    retake: 'మళ్ళీ తీయండి',
    results: 'గుర్తింపు ఫలితాలు',
    healthy: 'ఆరోగ్యకరమైనది',
    disease: 'వ్యాధి గుర్తించబడింది',
    warning: 'హెచ్చరిక',
    confidence: 'నమ్మకం',
    weatherAlert: 'వాతావరణ హెచ్చరిక',
    advice: 'చికిత్స సలహా',
    fertilizer: 'ఎరువుల సిఫార్సు',
    temp: 'ఉష్ణోగ్రత',
    rain: 'వర్షం అవకాశం',
    smartAlertRain: 'వర్షం వచ్చే అవకాశం ఉంది: ఈ రోజు ఎరువులు చల్లడం మానుకోండి.',
    smartAlertHeat: 'ఎక్కువ వేడి: పంటలను రక్షించడానికి నీటి పారుదల పెంచండి.',
    smartAlertClear: 'వాతావరణం నిర్మలంగా ఉంది: నిర్వహణకు మంచి సమయం.',
    voiceOutput: 'ఫలితాలను వినండి',
    placeholderName: 'మీ పేరు నమోదు చేయండి',
    placeholderEmail: 'ఫోన్ లేదా ఈమెయిల్ నమోదు చేయండి',
    placeholderPass: 'పాస్‌వర్డ్ నమోదు చేయండి',
    landSize: 'భూమి పరిమాణం (ఎకరాలు)',
    placeholderLand: 'మీకు ఎన్ని ఎకరాల భూమి ఉంది?',
    cropDetails: 'పంట వివరాలు',
    cropVariety: 'పంట రకం',
    soilType: 'నేల రకం',
    plantingDate: 'నాటిన తేదీ',
    next: 'తరువాత',
    dosageInfo: 'ఎరువుల మోతాదు',
    totalQuantity: 'అవసరమైన మొత్తం పరిమాణం',
    buyNow: 'ఎరువులను ఆన్‌లైన్‌లో కొనండి',
    profile: 'రైతు ప్రొఫైల్',
    knowledgeHub: 'నాలెడ్జ్ హబ్',
    perAcre: 'ఎకరానికి',
    totalFor: 'మొత్తం',
    acres: 'ఎకరాలు',
    welcomeTitle: 'స్వాగతం',
    welcomeSubtitle: 'వ్యవసాయ భవిష్యత్తును తీర్చిదిద్దుతున్నాము, ప్రతి ఆకుతో।',
    welcomeMessage: 'స్మార్ట్ వ్యవసాయం కోసం మీ AI-ఆధారిత తోడు। వ్యాధులను గుర్తించండి, వాతావరణ హెచ్చరికలను పొందండి మరియు ఎరువుల మోతాదును ఆప్టిమైజ్ చేయండి - అన్నీ ఒకే చోట।',
    getStarted: 'వ్యవసాయం ప్రారంభించండి',
    joinCommunity: 'కమ్యూనిటీలో చేరండి',
    welcomeBack: 'మళ్ళీ స్వాగతం',
    cotton: 'ప్రత్తి',
    quintal: '/ క్వింటాల్',
  },
  kn: {
    appName: 'ಕ್ರಾಪ್ ಕೇರ್ AI',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    logout: 'ಲಾಗೌಟ್',
    name: 'ಪೂರ್ಣ ಹೆಸರು',
    emailPhone: 'ಫೋನ್ ಅಥವಾ ಇಮೇಲ್',
    password: 'ಪಾಸ್ವರ್ಡ್',
    noAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
    hasAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?',
    scan: 'ಸ್ಕ್ಯಾನ್',
    history: 'ಇತಿಹಾಸ',
    home: 'ಹೋಮ್',
    uploadTitle: 'ಎಲೆಯ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    uploadDesc: 'ರೋಗಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಲು ಪೀಡಿತ ಸಸ್ಯದ ಎಲೆಯ ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ.',
    analyze: 'ವಿಶ್ಲೇಷಿಸಿ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    retake: 'ಮತ್ತೆ ತೆಗೆಯಿರಿ',
    results: 'ಪತ್ತೆ ಹಚ್ಚುವ ಫಲಿತಾಂಶಗಳು',
    healthy: 'ಆರೋಗ್ಯಕರ',
    disease: 'ರೋಗ ಪತ್ತೆಯಾಗಿದೆ',
    warning: 'ಎಚ್ಚರಿಕೆ',
    confidence: 'ನಂಬಿಕೆ',
    weatherAlert: 'ಹವಾಮಾನ ಮುನ್ನೆಚ್ಚರಿಕೆ',
    advice: 'ಚಿಕಿತ್ಸಾ ಸಲಹೆ',
    fertilizer: 'ಗೊಬ್ಬರ ಶಿಫਾਰಸು',
    temp: 'ತಾಪಮಾನ',
    rain: 'ಮಳೆ ಸಾಧ್ಯತೆ',
    smartAlertRain: 'ಮಳೆ ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ: ಇಂದು ಗೊಬ್ಬರ ಸಿಂಪಡಿಸುವುದನ್ನು ತಪ್ಪಿಸಿ.',
    smartAlertHeat: 'ಹೆಚ್ಚಿನ ಶಾಖ: ಬೆಳೆಗಳನ್ನು ರಕ್ಷಿಸಲು ನೀರாவರಿ ಹೆಚ್ಚಿಸಿ.',
    smartAlertClear: 'ಹವಾಮಾನ ಸ್ಪಷ್ಟವಾಗಿದೆ: ನಿರ್ವಹಣೆಗೆ ಉತ್ತಮ ಸಮಯ.',
    voiceOutput: 'ಫಲಿತಾಂಶಗಳನ್ನು ಆಲಿಸಿ',
    placeholderName: 'ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂદಿಸಿ',
    placeholderEmail: 'ಫೋನ್ ಅಥವಾ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    placeholderPass: 'ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
    landSize: 'ಭೂಮಿಯ ಗಾತ್ರ (ಎಕರೆ)',
    placeholderLand: 'ನಿಮ್ಮಲ್ಲಿ ಎಷ್ಟು ಎಕರೆ ಭೂಮಿ ಇದೆ?',
    cropDetails: 'ಬೆಳೆ ವಿವರಗಳು',
    cropVariety: 'ಬೆಳೆ ವಿಧ',
    soilType: 'ಮಣ್ಣಿನ ವಿಧ',
    plantingDate: 'ನಾಟಿ ದಿನಾಂక',
    next: 'ಮುಂದೆ',
    dosageInfo: 'ಗೊಬ್ಬರದ ಪ್ರಮಾಣ',
    totalQuantity: 'ಅಗತ್ಯವಿರುವ ಒಟ್ಟು ಪ್ರಮಾಣ',
    buyNow: 'ಗೊಬ್ಬರವನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಖರೀದಿಸಿ',
    profile: 'ರೈತ ಪ್ರොಫೈಲ್',
    knowledgeHub: 'ಜ್ಞಾನ ಕೇಂದ್ರ',
    perAcre: 'ಪ್ರತಿ ಎಕರೆಗೆ',
    totalFor: 'ಒಟ್ಟು',
    acres: 'ಎಕರೆ',
    welcomeTitle: 'ಸುಸ್ವಾಗತ',
    welcomeSubtitle: 'ಕೃಷಿಯ ಭವಿಷ್ಯವನ್ನು ಪೋಷಿಸುತ್ತಿದ್ದೇವೆ, ಪ್ರತಿ ಎಲೆಯೊಂದಿಗೆ।',
    welcomeMessage: 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿಗಾಗಿ ನಿಮ್ಮ AI-ಚಾಲಿತ ಸಂಗಾತಿ। ರೋಗಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಿ, ಹವಾಮಾನ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳನ್ನು ಪಡೆಯಿರಿ ಮತ್ತು ಗೊಬ್ಬರದ ಪ್ರಮಾಣವನ್ನು ಉತ್ತಮಗೊಳಿಸಿ - ಎಲ್ಲವೂ ಒಂದೇ ಕಡೆ।',
    getStarted: 'ಕೃಷಿ ಆರಂಭಿಸಿ',
    joinCommunity: 'ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    cotton: 'ಹತ್ತಿ',
    quintal: '/ ಕ್ವಿಂಟಾಲ್',
  },
  ml: {
    appName: 'ക്രോപ് കെയർ AI',
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    logout: 'ലോഗൗട്ട്',
    name: 'പൂർണ്ണനാമം',
    emailPhone: 'ഫോൺ അല്ലെങ്കിൽ ഇമെയിൽ',
    password: 'പാസ്‌വേഡ്',
    noAccount: "അക്കൗണ്ട് ഇല്ലേ?",
    hasAccount: 'നിലവിൽ അക്കൗണ്ട് ഉണ്ടോ?',
    scan: 'സ്കാൻ',
    history: 'ചരിത്രം',
    home: 'ഹോം',
    uploadTitle: 'ഇലയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    uploadDesc: 'രോഗങ്ങൾ കണ്ടെത്താൻ ബാധിച്ച ചെടിയുടെ ഇലയുടെ ഫോട്ടോ എടുക്കുക.',
    analyze: 'വിശകലനം ചെയ്യുക',
    analyzing: 'വിശകലനം ചെയ്യുന്നു...',
    retake: 'വീണ്ടും എടുക്കുക',
    results: 'കണ്ടെത്തൽ ഫലങ്ങൾ',
    healthy: 'ആരോഗ്യമുള്ളത്',
    disease: 'രോഗം കണ്ടെത്തി',
    warning: 'മുന്നറിയിപ്പ്',
    confidence: 'വിശ്വാസ്യത',
    weatherAlert: 'കാലാവസ്ഥാ മുന്നറിയിപ്പ്',
    advice: 'ചികിത്സാ ഉപദേശം',
    fertilizer: 'വളപ്രയോഗ ശുപാർശ',
    temp: 'താപനില',
    rain: 'മഴ സാധ്യത',
    smartAlertRain: 'മഴ പ്രതീക്ഷിക്കുന്നു: ഇന്ന് വളം തളിക്കുന്നത് ഒഴിവാക്കുക.',
    smartAlertHeat: 'കഠിനമായ ചൂട്: വിളകളെ സംരക്ഷിക്കാൻ ജലസേചനം വർദ്ധിപ്പിക്കുക.',
    smartAlertClear: 'കാലാവಸ್ಥ തെളിഞ്ഞതാണ്: പരിപാലനത്തിന് നല്ല സമയം.',
    voiceOutput: 'ഫലങ്ങൾ കേൾക്കുക',
    placeholderName: 'നിങ്ങളുടെ പേര് നൽകുക',
    placeholderEmail: 'ഫോൺ അല്ലെങ്കിൽ ഇമെയിൽ നൽകുക',
    placeholderPass: 'പാസ്‌വേഡ് നൽകുക',
    landSize: 'സ്ഥലത്തിന്റെ അളവ് (ഏക്കർ)',
    placeholderLand: 'നിങ്ങൾക്ക് എത്ര ഏക്കർ സ്ഥലമുണ്ട്?',
    cropDetails: 'വിള വിവരങ്ങൾ',
    cropVariety: 'വിള ഇനം',
    soilType: 'മണ്ണിന്റെ തരം',
    plantingDate: 'നട്ട തീയതി',
    next: 'അടുത്തത്',
    dosageInfo: 'വളത്തിന്റെ അളവ്',
    totalQuantity: 'ആവശ്യമായ മൊത്തം അളവ്',
    buyNow: 'വളം ഓൺലൈനായി വാങ്ങുക',
    profile: 'കർഷക പ്രൊഫൈൽ',
    knowledgeHub: 'വിജ്ഞാന കേന്ദ്രം',
    perAcre: 'ഏക്കറിന്',
    totalFor: 'ആകെ',
    acres: 'ஏக்கர்',
    welcomeTitle: 'സ്വാഗതം',
    welcomeSubtitle: 'കൃഷിയുടെ ഭാവി പരിപാലിക്കുന്നു, ഓരോ ഇലയിലും।',
    welcomeMessage: 'സ്മാർട്ട് കൃഷിക്കായി നിങ്ങളുടെ AI-അധിഷ്ഠിത കൂട്ടാളി। രോഗങ്ങൾ കണ്ടെത്തുക, കാലാവസ്ഥാ മുന്നറിയിപ്പുകൾ നേടുക, വളത്തിന്റെ അളവ് കൃത്യമാക്കുക - എല്ലാം ഒരിടത്ത്।',
    getStarted: 'കൃഷി ആരംഭിക്കുക',
    joinCommunity: 'കൂട്ടായ്മയിൽ ചേരുക',
    welcomeBack: 'വീണ്ടും സ്വാഗതം',
    cotton: 'പരുത്തി',
    quintal: '/ ക്വിന്റൽ',
  },
  gu: {
    appName: 'ક્રોપકેર AI',
    login: 'લોગિન',
    signup: 'સાઇન અપ',
    logout: 'લોગઆઉટ',
    name: 'પૂરું નામ',
    emailPhone: 'ફોન અથવા ઇમેઇલ',
    password: 'પાસવર્ડ',
    noAccount: "ખાતું નથી?",
    hasAccount: 'પહેલેથી ખાતું છે?',
    scan: 'સ્કેન',
    history: 'ઇતિહાસ',
    home: 'હોમ',
    uploadTitle: 'પાનનો ફોટો અપલોડ કરો',
    uploadDesc: 'રોગો શોધવા માટે અસરગ્રસ્ત છોડના પાનનો ફોટો લો.',
    analyze: 'વિશ્લેષણ કરો',
    analyzing: 'વિશ્લેષણ થઈ રહ્યું છે...',
    retake: 'ફરીથી લો',
    results: 'તપાસના પરિણામો',
    healthy: 'તંદુરસ્ત',
    disease: 'રોગ જણાયો',
    warning: 'ચેતવણી',
    confidence: 'વિશ્વાસ',
    weatherAlert: 'હવામાન ચેતવણી',
    advice: 'સારવારની સલાહ',
    fertilizer: 'ખાતરની ભલામણ',
    temp: 'તાપમાન',
    rain: 'વરસાદની શક્યતા',
    smartAlertRain: 'વરસાદની અપેક્ષા છે: આજે ખાતર છાંટવાનું ટાળો.',
    smartAlertHeat: 'વધારે ગરમી: પાકને બચાવવા માટે સિંચાઈ વધારો.',
    smartAlertClear: 'હવામાન ચોખ્ખું છે: જાળવણી માટે સારો સમય.',
    voiceOutput: 'પરિણામો સાંભળો',
    placeholderName: 'તમારું નામ દાખલ કરો',
    placeholderEmail: 'ફોન અથવા ઇમેઇલ દાખલ કરો',
    placeholderPass: 'પાસવર્ડ દાખલ કરો',
    landSize: 'જમીનનું કદ (એકર)',
    placeholderLand: 'તમારી પાસે કેટલી એકર જમીન છે?',
    cropDetails: 'પાકની વિગતો',
    cropVariety: 'પાકની જાત',
    soilType: 'જમીનનો પ્રકાર',
    plantingDate: 'વાવેતરની તારીખ',
    next: 'આગળ',
    dosageInfo: 'ખાતરનું પ્રમાણ',
    totalQuantity: 'જરૂરી કુલ જથ્થો',
    buyNow: 'ઓનલાઇન ખાતર ખરીદો',
    profile: 'ખેડૂત પ્રોફાઇલ',
    knowledgeHub: 'જ્ઞાન કેન્દ્ર',
    perAcre: 'એકર દીઠ',
    totalFor: 'કુલ',
    acres: 'એકર',
    welcomeTitle: 'સુસ્વાગતમ',
    welcomeSubtitle: 'ખેતીના ભવિષ્યને સંવારવું, દરેક પાન સાથે।',
    welcomeMessage: 'સ્માર્ટ ખેતી માટે તમારો AI-આધારિત સાથી। રોગો શોધો, હવામાન ચેતવણીઓ મેળવો અને ખાતરનું પ્રમાણ સચોટ કરો - બધું એક જ જગ્યાએ।',
    getStarted: 'ખેતી શરૂ કરો',
    joinCommunity: 'સમુદાયમાં જોડાઓ',
    welcomeBack: 'ફરી સ્વાગત છે',
    cotton: 'કપાસ',
    quintal: '/ ક્વિન્ટલ',
  },
  pa: {
    appName: 'ਕਰੌਪਕੇਅਰ AI',
    login: 'ਲੌਗਇਨ',
    signup: 'ਸਾਈਨ ਅੱਪ',
    logout: 'ਲੌਗਆਉਟ',
    name: 'ਪੂਰਾ ਨਾਮ',
    emailPhone: 'ਫੋਨ ਜਾਂ ਈਮੇਲ',
    password: 'ਪਾਸਵਰਡ',
    noAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
    hasAccount: 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?',
    scan: 'ਸਕੈਨ',
    history: 'ਇਤਿਹਾਸ',
    home: 'ਹੋਮ',
    uploadTitle: 'ਪੱਤੇ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ',
    uploadDesc: 'ਬਿਮਾਰੀਆਂ ਦਾ ਪਤਾ ਲਗਾਉਣ ਲਈ ਪ੍ਰਭਾਵਿਤ ਪੌਦੇ ਦੇ ਪੱਤੇ ਦੀ ਫੋਟோ ਲਓ।',
    analyze: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...',
    retake: 'ਦੁਬਾਰਾ ਲਓ',
    results: 'ਜਾਂਚ ਦੇ ਨਤੀਜੇ',
    healthy: 'ਤੰਦਰੁਸਤ',
    disease: 'ਬਿਮਾਰੀ ਦਾ ਪਤਾ ਲੱਗਾ',
    warning: 'ਚੇਤਾਵਨੀ',
    confidence: 'ਭਰੋਸਾ',
    weatherAlert: 'ਮੌਸਮ ਦੀ ਚੇਤਾਵਨੀ',
    advice: 'ਇਲਾਜ ਦੀ ਸਲਾਹ',
    fertilizer: 'ਖਾਦ ਦੀ ਸਿਫਾਰਸ਼',
    temp: 'ਤਾਪਮਾਨ',
    rain: 'ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ',
    smartAlertRain: 'ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ ਹੈ: ਅੱਜ ਖਾਦ ਛਿੜਕਣ ਤੋਂ ਬਚੋ।',
    smartAlertHeat: 'ਬਹੁਤ ਗਰਮੀ: ਫਸਲਾਂ ਦੀ ਰਾਖੀ ਲਈ ਸਿੰਚਾਈ ਵਧਾਓ।',
    smartAlertClear: 'ਮੌਸਮ ਸਾਫ ਹੈ: ਸਾਂਭ-ਸੰਭਾਲ ਲਈ ਚੰਗਾ ਸਮਾਂ ਹੈ।',
    voiceOutput: 'ਨਤੀਜੇ ਸੁਣੋ',
    placeholderName: 'ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    placeholderEmail: 'ਫੋਨ ਜਾਂ ਈਮੇਲ ਦਰਜ ਕਰੋ',
    placeholderPass: 'ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
    landSize: 'ਜ਼ਮੀਨ ਦਾ ਆਕਾਰ (ਏਕੜ)',
    placeholderLand: 'ਤੁਹਾਡੇ ਕੋਲ ਕਿੰਨੀ ਏਕੜ ਜ਼ਮੀਨ ਹੈ?',
    cropDetails: 'ਫਸਲ کے ਵੇਰਵੇ',
    cropVariety: 'ਫਸਲ ਦੀ ਕਿਸਮ',
    soilType: 'ਮਿੱਟੀ ਦੀ ਕਿਸਮ',
    plantingDate: 'ਬਿਜਾਈ ਦੀ ਮਿਤੀ',
    next: 'ਅੱਗੇ',
    dosageInfo: 'ਖਾਦ ਦੀ ਮਾਤਰਾ',
    totalQuantity: 'ਕੁੱલ ਲੋੜੀਂਦੀ ਮਾਤરા',
    buyNow: 'ਆਨਲਾਈਨ ਖਾਦ ਖਰੀਦੋ',
    profile: 'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ',
    knowledgeHub: 'ਗਿਆਨ ਕੇਂਦਰ',
    perAcre: 'ਪ੍ਰਤੀ ਏਕੜ',
    totalFor: 'ਕੁੱਲ',
    acres: 'ਏਕੜ',
    welcomeTitle: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    welcomeSubtitle: 'ਖੇਤੀਬਾੜੀ ਦੇ ਭਵਿੱਖ ਨੂੰ ਸੰਵਾਰਨਾ, ਹਰ ਇੱਕ ਪੱਤੇ ਨਾਲ।',
    welcomeMessage: 'ਸਮਾਰਟ ਖੇਤੀ ਲਈ ਤੁਹਾਡਾ AI-ਆਧਾਰਿਤ ਸਾਥੀ। ਬਿਮਾਰੀਆਂ ਦਾ ਪਤਾ ਲਗਾਓ, ਮੌਸਮ ਦੀਆਂ ਚੇਤਾਵਨੀਆਂ ਪ੍ਰਾਪਤ ਕਰੋ ਅਤੇ ਖਾਦ ਦੀ ਮਾਤਰਾ ਨੂੰ ਅਨੁਕੂਲ ਬਣਾਓ - ਸਭ ਕੁਝ ਇੱਕੋ ਥਾਂ ਤੇ।',
    getStarted: 'ਖੇਤੀ ਸ਼ੁਰੂ ਕਰੋ',
    joinCommunity: 'ਭਾਈਚਾਰੇ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    cotton: 'ਕਪਾਹ',
    quintal: '/ ਕੁਇੰਟਲ',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    // Basic location-based language detection logic
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          // In a real app, you'd use a reverse geocoding API to get the country/region
          // For this demo, we'll simulate or stick to English unless the user changes it
          // or we could check browser language
          const browserLang = (navigator.language || '').split('-')[0];
          if (['en', 'bn', 'hi', 'mr', 'ta', 'te', 'kn', 'ml', 'gu', 'pa'].includes(browserLang)) {
            // setLanguage(browserLang);
          }
        },
        () => console.log("Location access denied, defaulting to English")
      );
    }
  }, []);

  const t = (key) => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    return translations['en'][key] || key;
  };

  const toggleLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
